

PROG = pagedir
MAKE = make



.PHONY: dtest ctest clean

ctest:
	mkdir ../tsetest
	mkdir ../tsetest/index1
	mkdir ../tsetest/letters3
	mkdir ../tsetest/wiki2
	mkdir ../tsetest/scrape2

dtest:
	rm -rf ../tsetest

clean:
	rm -f *~ *.o
	rm -f $(PROG)
